# Generated by Django 4.0.6 on 2023-12-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_news_body_ru_news_body_uz_news_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.FileField(upload_to='hotels', verbose_name='Логотип')),
                ('star', models.PositiveIntegerField(verbose_name='Количество звезд')),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние до мечети')),
                ('image1', models.ImageField(upload_to='hotels', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Изображение 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='Изображение 5')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('subtitle_uz', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('body_uz', models.TextField(null=True, verbose_name='Текст')),
                ('body_ru', models.TextField(null=True, verbose_name='Текст')),
                ('image1', models.ImageField(upload_to='transport', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='transport', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='transport', verbose_name='Изображение 3')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
