# Generated by Django 4.0.6 on 2023-12-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_hotel_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст')),
                ('body_uz', models.TextField(null=True, verbose_name='Текст')),
                ('body_ru', models.TextField(null=True, verbose_name='Текст')),
                ('start_time', models.DateField(verbose_name='Дата начала')),
                ('end_time', models.DateField(verbose_name='Дата окончания')),
                ('days_in_Makkah', models.PositiveIntegerField(verbose_name='Количество дней в Мекке')),
                ('days_in_Madinah', models.PositiveIntegerField(verbose_name='Количество дней в Медине')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('Madinah_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madinah_hotel', to='common.hotel', verbose_name='Отель в Медине')),
                ('Makkah_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makkah_hotel', to='common.hotel', verbose_name='Отель в Мекке')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TarifService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.service', verbose_name='Услуга')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Услуга тарифа',
                'verbose_name_plural': 'Услуги тарифов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TarifPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people_count', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Цена тарифа',
                'verbose_name_plural': 'Цены тарифов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('month', models.CharField(max_length=255, verbose_name='Месяц')),
                ('people_count', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.tarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
