# Generated by Django 4.0.6 on 2023-12-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_hotel_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifservice',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='common.tarif', verbose_name='Тариф'),
        ),
    ]
