# Generated by Django 4.0.6 on 2024-01-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_news_body_alter_news_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tarifpricing',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='common.tarif', verbose_name='Тариф'),
        ),
    ]
