# Generated by Django 4.0.6 on 2024-01-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location_url',
        ),
    ]
